---
version: "3.8"

services:
  node:
    image: node:20.12.2-alpine
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    ports:
      - 5173:5173
    volumes:
      - .:/home/node
